### ISSUE TITLE
Dictionary Data Source

### ISSUE THREAD

**Issue by FengYusheng** [haikalzain/arabic-dict-chrome#1]
Hi haikanlzain,

Thanks for you created this greate tool. You can call me Yusheng. I'm a developer from China.

I'm looking for a dictionary which can be used by **Hunspell** for Arabic morphological analyzer

I hope when I input an Arabic word into hunspell, hunspell returns the stem of the word.

I realized this greate tool could return a root form for the word's grammer varients.

I want to know where you got the dictionary data and if it's possible to convert it into hunspell format.

Best Regards,
Yusheng

**Comment by mr-islam** [comment]
Hi, I just came across this issue so sorry for the late reply

The dictionary used in this app is the AraTools dataset: http://aratools.com/

**Comment by FengYusheng** [comment]
Thanks, @mr-islam , I'll look into it. I closed this issue for now
