### ISSUE TITLE
Team up on project to add Arabic to an app

### ISSUE THREAD

**Issue by Noitidart** [haikalzain/arabic-dict-chrome#2]
Salaam, would you be available to teaming up on a project to add Arabic translation to an app (im not sure of platform yet) - please email me if available at noitidart@gmail

**Comment by haikalzain** [comment]
Salam, what are you trying to build?

**Comment by Noitidart** [comment]
Thank you!

Islamicity.com has a Quran web app - https://www.islamicity.org/quran/ - and they have your Arabic Dictionary extension for Chrome installed for our Quran search. Please see the screenshot below. When you hover over the Arabic, it gives you the root and definition.

They wanted to see if we can make this native for our Quran https://www.islamicity.org/quran without installing the extension that could show the same on any browser.
 
Eventually, we would want to make this a native iOS and Android app
 

If you are interested and available please shoot me an email.

**Comment by haikalzain** [comment]
taking this offline
